import * as FEAAS from '@sitecore-feaas/clientside/react'
import React, { useState } from 'react';
import { Box, Button, Text } from '@chakra-ui/react';

const ConsentCookieBanner = () => {
  const [showBanner, setShowBanner] = useState(true);

  const handleAccept = () => {
    // Set cookie consent logic here
    setShowBanner(false);
  };

  return (
    <>
      {showBanner && (
        <Box
          bg="gray.900"
          color="white"
          p={4}
          position="fixed"
          bottom={0}
          left={0}
          width="100%"
          zIndex={9999}
        >
          <Text>
            We use cookies to enhance your experience. By continuing to use our site, you consent to the use of cookies.
          </Text>
          <Button
            colorScheme="blue"
            ml={4}
            onClick={handleAccept}
          >
            Accept
          </Button>
        </Box>
      )}
    </>
  );
};

FEAAS.registerComponent(ConsentCookieBanner, {
  name: 'clientside-only',
  title: 'Clientside-only component',
  description: 'This is a Consent Cookie Banner Generated by AI',
  thumbnail: 'https://mss-p-006-delivery.stylelabs.cloud/api/public/content/3a7a2ded-6e7d-4f0e-9ce5-bb5eef0a7799',
  group: 'AI Generated Components',
  required: [],
  properties: {}
})

export default ConsentCookieBanner;