import * as FEAAS from '@sitecore-feaas/clientside/react';
import React from 'react';
import { Box, Button, FormControl, FormLabel, Input, Textarea, VStack } from '@chakra-ui/react';

const ContactForm = () => {
  const handleSubmit = (e) => {
    e.preventDefault();
    // Handle form submission logic here
  };

  return (
    <Box p={4}>
      <form onSubmit={handleSubmit}>
        <VStack spacing={4} align="stretch">
          <FormControl>
            <FormLabel htmlFor="name">Name</FormLabel>
            <Input type="text" id="name" name="name" required />
          </FormControl>

          <FormControl>
            <FormLabel htmlFor="email">Email</FormLabel>
            <Input type="email" id="email" name="email" required />
          </FormControl>

          <FormControl>
            <FormLabel htmlFor="message">Message</FormLabel>
            <Textarea id="message" name="message" rows={5} required />
          </FormControl>

          <Button type="submit" colorScheme="blue">Submit</Button>
        </VStack>
      </form>
    </Box>
  );
};

FEAAS.registerComponent(ContactForm, {
  name: 'contact-form',
  title: 'ContactForm',
  description: 'This is a Contact Form Generated by AI',
  thumbnail: 'https://mss-p-006-delivery.stylelabs.cloud/api/public/content/3997aaa0d8be4eb789f3b1541bd95c58',
  group: 'AI Generated Components',
  required: [],
  properties: {}
});

export default ContactForm;
