import * as FEAAS from '@sitecore-feaas/clientside/react';
import {
  Box,
  Button,
  FormControl,
  FormErrorMessage,
  FormLabel,
  Input,
  VStack,
} from '@chakra-ui/react';
import React from 'react';

export default function ContactForm({ formTitle, ctaText }) {
  const handleSubmit = async (event) => {
    event.preventDefault();
    const email = event.target.elements.email.value;
    const name = event.target.elements.name.value;
    const phone = event.target.elements.phone.value;

    const formData = {
      Email: email,
      Name: name,
      Mobile: phone,
    };

    try {
      const response = await fetch(
        'https://api.sitecoresend.io/v3/subscribers/b4b8f865-d8fa-4a34-ba59-02b1d7205561/subscribe.json?apikey=90789a3a-f1ef-4798-a8b4-18c5981b03ae',
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(formData),
        }
      );

      if (response.ok) {
        // Handle successful form submission
        console.log('Form submitted successfully');
      } else {
        // Handle form submission error
        console.error('Failed to submit form');
      }
    } catch (error) {
      // Handle form submission error
      console.error('Failed to submit form', error);
    }
  };

  return (
    <Box
      maxW={{ base: 'sm', md: 'md' }}
      mx='auto'
      py={8}
      px={{ base: '4', md: '8' }}
      bg='white'
      borderRadius='md'
      boxShadow='md'
    >
      <form onSubmit={handleSubmit}>
        <VStack spacing={6}>
          <Box>
            <FormLabel
              htmlFor='title'
              fontSize='2xl'
              color='blue.500'
              fontWeight='bold'
            >
              {formTitle}
            </FormLabel>
          </Box>
          <Box>
            <FormLabel htmlFor='name'>Name</FormLabel>
            <FormControl id='name' isRequired>
              <Input type='text' name='name' />
            </FormControl>
          </Box>
          <Box>
            <FormLabel htmlFor='email'>Email</FormLabel>
            <FormControl id='email' isRequired>
              <Input type='email' name='email' />
            </FormControl>
          </Box>
          <Box>
            <FormLabel htmlFor='phone'>Phone</FormLabel>
            <FormControl id='phone' isRequired>
              <Input type='tel' name='phone' />
            </FormControl>
          </Box>
          <Button type='submit' colorScheme='blue' size='lg'>
            {ctaText}
          </Button>
        </VStack>
      </form>
    </Box>
  );
}

FEAAS.registerComponent(ContactForm, {
  name: 'contact-form-ai',
  title: 'Contact Form Generated by AI',
  description: 'This is a Contact Form generated by AI.',
  thumbnail:
    'https://mss-p-006-delivery.stylelabs.cloud/api/public/content/3997aaa0d8be4eb789f3b1541bd95c58',
  group: 'AI Generated Components',
  properties: {
    formTitle: {
      type: 'string',
      title: 'Form Title',
    },
    ctaText: {
      type: 'string',
      title: 'CTA Text',
    },
  },
});