'use client'
import * as FEAAS from '@sitecore-feaas/clientside/react'
import React from 'react';  
import { Box, VStack, HStack, Text } from '@chakra-ui/react';  

const FilmSchedule = ({ movies }) => {  
  return (  
    <Box w="100%" p={4}>  
      <VStack spacing={4} alignItems="start">  
        {movies.slice(0, 6).map((movie, index) => (  
          <HStack key={index} spacing={4}>  
            <Text fontSize="lg" fontWeight="bold" color="gray.700">  
              {movie.title}  
            </Text>  
            <Text fontSize="lg" color="gray.500">  
              {movie.cinemaTimes.join(', ')}  
            </Text>  
          </HStack>  
        ))}  
      </VStack>  
    </Box>  
  );  
};  

FEAAS.registerComponent(FilmSchedule , {
  name: 'film-schedule',
  title: 'FilmSchedule',
  description: 'This is a Film Schedule Component Generated by AI',
  thumbnail: 'https://mss-p-006-delivery.stylelabs.cloud/api/public/content/3997aaa0d8be4eb789f3b1541bd95c58',
  group: 'AI Generated Components',
  properties: {
    movies: {
      type: 'array',
      title: 'Movies',
      items: {
        type: 'object',
        title: 'Movie',
        properties: {
          title: {
            type: 'string',
            title: 'Title'
          },
          cinemaTimes: {
            type: 'array',
            title: 'Cinema Times',
            items: {
              type: 'string',
              title: 'Time'
            }
          }
        }
      }
    }
  }
})

export default FilmSchedule;