'use client'
import * as FEAAS from '@sitecore-feaas/clientside/react'
import React from 'react';  
import { Box, Flex, Heading, Input, Button, Text } from '@chakra-ui/react';  
  
const Form = ({ title }) => {  
  return (  
    <Flex  
      justifyContent="center"  
      alignItems="center"  
      h="100vh"  
    >  
      <Box  
        p={4}  
        w="400px"  
        borderWidth={1}  
        borderRadius="md"  
      >  
        <Heading as="h2" size="lg" mb={4} color="blue.500">  
          {title}  
        </Heading>  
        <Flex  
          flexDirection="column"  
          gap={4}  
        >  
          <Input type="text" placeholder="Email" />  
          <Input type="text" placeholder="Name" />  
          <Input type="text" placeholder="Phone" />  
          <Button colorScheme="blue" mt={4}>Submit</Button>
        </Flex>  
      </Box>  
    </Flex>  
  );  
};  
 
FEAAS.registerComponent(Form, {
  name: 'form',
  title: 'Form',
  description: 'This is a Form Generated by AI',
  thumbnail: 'https://mss-p-006-delivery.stylelabs.cloud/api/public/content/3997aaa0d8be4eb789f3b1541bd95c58',
  group: 'AI Generated Components',
  required: ['title'],
  properties: {
    title: {
      type: 'string',
      title: 'title'
    },
  }
})

export default Form;