import * as FEAAS from '@sitecore-feaas/clientside/react'
import React from 'react';  
import { Box, Flex, Heading, Text, useColorModeValue } from '@chakra-ui/react';  
  
const HeroCustomSection = ({ backgroundImage, title, subtitle, description }) => {  
  const bgColor = useColorModeValue('gray.800', 'gray.700');
  const textColor = useColorModeValue('white', 'gray.200');
  
  return (  
    <Box  
      background={`url(${backgroundImage}) center / cover`}  
      h="400px"  
      w="100%"  
      position="relative"  
    >  
      <Flex  
        h="100%"  
        w="100%"  
        justifyContent="center"  
        alignItems="center"  
        flexDirection="column"  
        bg={bgColor}  
      >  
        <Heading as="h1" color={textColor} fontSize="5xl">  
          {title}  
        </Heading>  
        <Text as="h2" color={textColor} fontSize="xl">  
          {subtitle}  
        </Text>  
        <Text as="p" color={textColor} fontSize="md">
          {description}
        </Text>
      </Flex>  
    </Box>  
  );  
};  

FEAAS.registerComponent(HeroCustomSection, {
  name: 'clientside-only',
  title: 'Clientside-only component',
  description: 'This is a Hero Custom Section Generated by AI. It allows you to display a hero section with a custom background image, title, subtitle, and description. The component supports dark mode and automatically adjusts the text color based on the background. Simply provide the URL of the background image, the title, subtitle, and description as props.',
  thumbnail: 'https://mss-p-006-delivery.stylelabs.cloud/api/public/content/3997aaa0d8be4eb789f3b1541bd95c58',
  group: 'AI Generated Components',
  required: ['backgroundImage'],
  properties: {
    backgroundImage: {
      type: 'string',
      title: 'backgroundImage'
    },
    title: {
      type: 'string',
      title: 'title'
    },
    subtitle : {
      type: 'string',
      title: 'title'
    },
    description : {
      type: 'string',
      title: 'description'
    }
  }
})

export default HeroCustomSection;