'use client'
import * as FEAAS from '@sitecore-feaas/clientside/react'
import React from 'react';  
import { Box, Flex, Heading, Text, useColorMode } from '@chakra-ui/react';  
  
const HeroSection = ({ backgroundImage, title, subtitle }) => {  
  const { colorMode } = useColorMode();
  
  return (  
    <Box  
      background={backgroundImage}  
      h="400px"  
      w="100%"  
      position="relative"  
    >  
      <Flex  
        h="100%"  
        w="100%"  
        justifyContent="center"  
        alignItems="center"  
        flexDirection="column"  
        bg={colorMode === "dark" ? "rgba(255, 255, 255, 0.3)" : "rgba(0, 0, 0, 0.3)"}  
      >  
        <Heading as="h1" color={colorMode === "dark" ? "white" : "red"} fontSize="5xl">  
          {title}  
        </Heading>  
        <Text as="h2" color={colorMode === "dark" ? "white" : "black"} fontSize="xl">  
          {subtitle}  
        </Text>  
        <Text as="p" color={colorMode === "dark" ? "white" : "black"} fontSize="md">
          This is a hero section in dark mode. Customize the title, subtitle, and background image to create an engaging hero section for your website.
        </Text>
      </Flex>  
    </Box>  
  );  
};  
 
FEAAS.registerComponent(HeroSection , {
  name: 'hero-section',
  title: 'HeroSection',
  description: 'This is a Hero Section in Dark Mode Generated by AI. Customize the title, subtitle, and background image to create an engaging hero section for your website.',
  thumbnail: 'https://mss-p-006-delivery.stylelabs.cloud/api/public/content/3997aaa0d8be4eb789f3b1541bd95c58',
  group: 'AI Generated Components',
  required: ['backgroundImage'],
  properties: {
    backgroundImage: {
      type: 'string',
      title: 'backgroundImage'
    },
    title: {
      type: 'string',
      title: 'title'
    },
    subtitle : {
      type: 'string',
      title: 'subtitle'
    }
  }
})


export default HeroSection;  
