import * as FEAAS from '@sitecore-feaas/clientside/react'
import React from 'react';  
import { Box, Flex, Heading, Text, useColorMode } from '@chakra-ui/react';  
  
const HeroSection = ({ title, subtitle }) => {  
  const { colorMode } = useColorMode();

  return (  
    <Box  
      bg={colorMode === 'dark' ? 'gray.900' : 'white'}
      color={colorMode === 'dark' ? 'white' : 'gray.900'}
      py={8}
    >
      <Flex  
        maxW="1200px"
        mx="auto"
        justifyContent="center"  
        alignItems="center"  
        flexDirection="column"  
      >  
        <Heading as="h1" fontSize="5xl" textAlign="center" mb={4}>  
          {title}  
        </Heading>  
        <Text as="h2" fontSize="xl" textAlign="center">  
          {subtitle}  
        </Text>  
      </Flex>  
    </Box>  
  );  
};  

FEAAS.registerComponent(HeroSection , {
  name: 'clientside-only',
  title: 'Clientside-only component',
  description: 'This is a Hero Section in Dark Mode Generated by AI',
  thumbnail: 'https://mss-p-006-delivery.stylelabs.cloud/api/public/content/3997aaa0d8be4eb789f3b1541bd95c58',
  group: 'AI Generated Components',
  required: ['title', 'subtitle'],
  properties: {
    title: {
      type: 'string',
      title: 'title'
    },
    subtitle : {
      type: 'string',
      title: 'subtitle'
    }
  }
})

export default HeroSection;