import * as FEAAS from '@sitecore-feaas/clientside/react'
import React from 'react';
import { Box, Flex, Heading, Text } from '@chakra-ui/react';

const HeroBanner = ({ backgroundImage, title, subtitle }) => {
  return (
    <Box
      background={`url(${backgroundImage}) center / cover`}
      h="400px"
      w="100%"
      position="relative"
    >
      <Flex
        h="100%"
        w="100%"
        justifyContent="center"
        alignItems="center"
        flexDirection="column"
        bg="rgba(0, 0, 0, 0.3)"
      >
        <Heading as="h1" color="red" fontSize="5xl">
          {title}
        </Heading>
        <Text as="h2" color="black" fontSize="2xl">
          {subtitle}
        </Text>
      </Flex>
    </Box>
  );
};

FEAAS.registerComponent(HeroBanner, {
  name: 'hero-banner',
  title: 'Hero Banner',
  description: 'This is a Hero Banner generated by AI.',
  thumbnail: 'https://mss-p-006-delivery.stylelabs.cloud/api/public/content/3997aaa0d8be4eb789f3b1541bd95c58',
  group: 'AI Generated Components',
  required: ['backgroundImage'],
  properties: {
    backgroundImage: {
      type: 'string',
      title: 'Background Image'
    },
    title: {
      type: 'string',
      title: 'Title'
    },
    subtitle: {
      type: 'string',
      title: 'Subtitle'
    }
  }
});

export default HeroBanner;
