import * as FEAAS from '@sitecore-feaas/clientside/react'
import React from 'react';  
import { Box, Flex, Heading, Text, useColorModeValue } from '@chakra-ui/react';  
  
const HeroSection = ({ backgroundImage, title, subtitle }) => {  
  const bgColor = useColorModeValue('gray.800', 'gray.700');
  const textColor = useColorModeValue('white', 'gray.200');
  
  return (  
    <Box  
      background={`url(${backgroundImage}) center / cover`}  
      h="400px"  
      w="100%"  
      position="relative"  
    >  
      <Flex  
        h="100%"  
        w="100%"  
        justifyContent="center"  
        alignItems="center"  
        flexDirection="column"  
        bg={bgColor}  
      >  
        <Heading as="h1" color={textColor} fontSize="5xl">  
          {title}  
        </Heading>  
        <Text as="h2" color={textColor} fontSize="xl">  
          {subtitle}  
        </Text>  
      </Flex>  
    </Box>  
  );  
};  

FEAAS.registerComponent(HeroSection, {
  name: 'clientside-only',
  title: 'Clientside-only component',
  description: 'This is a Hero Section Generated by AI',
  thumbnail: 'https://mss-p-006-delivery.stylelabs.cloud/api/public/content/3997aaa0d8be4eb789f3b1541bd95c58',
  group: 'AI Generated Components',
  required: ['backgroundImage'],
  properties: {
    backgroundImage: {
      type: 'string',
      title: 'backgroundImage'
    },
    title: {
      type: 'string',
      title: 'title'
    },
    subtitle : {
      type: 'string',
      title: 'title'
    }
  }
})

export default HeroSection;