import * as FEAAS from '@sitecore-feaas/clientside/react'
import React from 'react';  
import { Box, Flex, Image } from '@chakra-ui/react';  
  
const ImageCarousel = ({ images }) => {  
  return (  
    <Box  
      w="100%"  
      position="relative"  
    >  
      <Flex  
        w="100%"  
        overflowX="scroll"  
        scrollSnapType="x mandatory"  
      >  
        {images.map((image, index) => (  
          <Image  
            key={index}  
            src={image}  
            objectFit="cover"  
            w="100%"  
            h="100%"  
            scrollSnapAlign="start"  
          />  
        ))}  
      </Flex>  
    </Box>  
  );  
};  
 
FEAAS.registerComponent(ImageCarousel, {
  name: 'clientside-only',
  title: 'Clientside-only component',
  description: 'This is an Image Carousel Generated by AI',
  thumbnail: 'https://mss-p-006-delivery.stylelabs.cloud/api/public/content/3997aaa0d8be4eb789f3b1541bd95c58',
  group: 'AI Generated Components',
  required: ['images'],
  properties: {
    images: {
      type: 'array',
      title: 'images',
      items: {
        type: 'string',
      }
    }
  }
})


export default ImageCarousel;