'use client'
import * as FEAAS from '@sitecore-feaas/clientside/react'
import React, { useRef } from 'react';
import { Box, IconButton } from '@chakra-ui/react';
import { FiPlay, FiPause, FiVolume2, FiVolumeX } from 'react-icons/fi';

const MinimalistVideoPlayer = ({ videoSrc }) => {
  const videoRef = useRef(null);
  const [isPlaying, setIsPlaying] = React.useState(false);
  const [isMuted, setIsMuted] = React.useState(false);

  const handlePlayPause = () => {
    const video = videoRef.current;
    if (video.paused) {
      video.play();
      setIsPlaying(true);
    } else {
      video.pause();
      setIsPlaying(false);
    }
  };

  const handleVolumeToggle = () => {
    const video = videoRef.current;
    video.muted = !video.muted;
    setIsMuted(!isMuted);
  };

  return (
    <Box position="relative">
      <video ref={videoRef} src={videoSrc} loop muted={isMuted} />

      <Box
        position="absolute"
        top="50%"
        left="50%"
        transform="translate(-50%, -50%)"
        display="flex"
        alignItems="center"
        justifyContent="center"
      >
        <IconButton
          onClick={handlePlayPause}
          variant="ghost"
          icon={isPlaying ? <FiPause /> : <FiPlay />}
          size="lg"
        />
        <IconButton
          onClick={handleVolumeToggle}
          variant="ghost"
          icon={isMuted ? <FiVolumeX /> : <FiVolume2 />}
          size="lg"
        />
      </Box>
    </Box>
  );
};

FEAAS.registerComponent(MinimalistVideoPlayer, {
  name: 'minimalist-video-player',
  title: 'MinimalistVideoPlayer',
  description: 'This is a Minimalist Video Player Generated by AI',
  thumbnail: 'https://mss-p-006-delivery.stylelabs.cloud/api/public/content/3997aaa0d8be4eb789f3b1541bd95c58',
  group: 'AI Generated Components',
  required: ['videoSrc'],
  properties: {
    videoSrc: {
      type: 'string',
      title: 'videoSrc'
    }
  }
})

export default MinimalistVideoPlayer;
