import * as FEAAS from '@sitecore-feaas/clientside/react'
import React from 'react';
import { Box, Flex, Heading, Text, Button } from '@chakra-ui/react';

const PricingPage = () => {
  return (
    <Box maxW="1200px" mx="auto" px={4} py={8}>
      <Heading as="h1" size="xl" textAlign="center" mb={8}>
        Pricing
      </Heading>
      <Flex justifyContent="center" alignItems="flex-start" flexWrap="wrap">
        <Box
          w={{ base: "100%", md: "45%", lg: "30%" }}
          bg="white"
          borderRadius="md"
          p={8}
          mb={4}
          shadow="md"
        >
          <Heading as="h2" size="lg" mb={4}>
            Basic Plan
          </Heading>
          <Text color="gray.500" fontSize="xl" mb={4}>
            $9.99/month
          </Text>
          <Text color="gray.500" fontSize="md" mb={4}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac
            tellus nec justo rutrum aliquet. Aliquam erat volutpat.
          </Text>
          <Button colorScheme="blue">Get Started</Button>
        </Box>
        <Box
          w={{ base: "100%", md: "45%", lg: "30%" }}
          bg="white"
          borderRadius="md"
          p={8}
          mb={4}
          shadow="md"
        >
          <Heading as="h2" size="lg" mb={4}>
            Pro Plan
          </Heading>
          <Text color="gray.500" fontSize="xl" mb={4}>
            $19.99/month
          </Text>
          <Text color="gray.500" fontSize="md" mb={4}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac
            tellus nec justo rutrum aliquet. Aliquam erat volutpat.
          </Text>
          <Button colorScheme="blue">Get Started</Button>
        </Box>
        <Box
          w={{ base: "100%", md: "45%", lg: "30%" }}
          bg="white"
          borderRadius="md"
          p={8}
          mb={4}
          shadow="md"
        >
          <Heading as="h2" size="lg" mb={4}>
            Enterprise Plan
          </Heading>
          <Text color="gray.500" fontSize="xl" mb={4}>
            $49.99/month
          </Text>
          <Text color="gray.500" fontSize="md" mb={4}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac
            tellus nec justo rutrum aliquet. Aliquam erat volutpat.
          </Text>
          <Button colorScheme="blue">Get Started</Button>
        </Box>
      </Flex>
    </Box>
  );
};

FEAAS.registerComponent(PricingPage , {
  name: 'clientside-only',
  title: 'Clientside-only component',
  description: 'This is a Pricing Page Generated by AI',
  thumbnail: 'https://mss-p-006-delivery.stylelabs.cloud/api/public/content/3997aaa0d8be4eb789f3b1541bd95c58',
  group: 'AI Generated Components'
});

export default PricingPage;