import * as FEAAS from '@sitecore-feaas/clientside/react'
import React from 'react';
import { Box, Flex, Heading, Text, Button } from '@chakra-ui/react';

const PricingPage = () => {
  return (
    <Box p={8} mx="auto" maxWidth="800px">
      <Heading as="h1" textAlign="center" mb={8}>
        Pricing
      </Heading>
      <Flex justifyContent="space-between" mb={8}>
        <Box flex="1" p={4} borderWidth={1} borderRadius="md">
          <Heading as="h2" size="lg" mb={4}>
            Basic Plan
          </Heading>
          <Text fontSize="xl" mb={4}>
            $9.99/month
          </Text>
          <Text mb={4}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
          </Text>
          <Button colorScheme="blue">Get Started</Button>
        </Box>
        <Box flex="1" p={4} borderWidth={1} borderRadius="md">
          <Heading as="h2" size="lg" mb={4}>
            Pro Plan
          </Heading>
          <Text fontSize="xl" mb={4}>
            $19.99/month
          </Text>
          <Text mb={4}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
          </Text>
          <Button colorScheme="blue">Get Started</Button>
        </Box>
        <Box flex="1" p={4} borderWidth={1} borderRadius="md">
          <Heading as="h2" size="lg" mb={4}>
            Enterprise Plan
          </Heading>
          <Text fontSize="xl" mb={4}>
            Contact Us
          </Text>
          <Text mb={4}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
          </Text>
          <Button colorScheme="blue">Contact Sales</Button>
        </Box>
      </Flex>
    </Box>
  );
};

FEAAS.registerComponent(PricingPage, {
  name: 'clientside-only',
  title: 'Clientside-only component',
  description: 'This is a Sleek Pricing Page Generated by AI',
  thumbnail: 'https://mss-p-006-delivery.stylelabs.cloud/api/public/content/3997aaa0d8be4eb789f3b1541bd95c58',
  group: 'AI Generated Components',
});

export default PricingPage;