import * as FEAAS from '@sitecore-feaas/clientside/react';
import React from 'react';
import { Box, Flex, Heading, Text, Button } from '@chakra-ui/react';

const PricingPage = () => {
  return (
    <Box>
      <Flex justifyContent="center" alignItems="center" h="100vh">
        <Box p={10} borderWidth={1} borderRadius="md" shadow="md">
          <Heading as="h1" size="xl" mb={6}>
            Pricing
          </Heading>
          <Flex justifyContent="space-between" mb={6}>
            <Box flex={1} mr={4}>
              <Heading as="h2" size="lg" mb={2}>
                Basic
              </Heading>
              <Text fontSize="xl" mb={2}>
                $9.99/month
              </Text>
              <Text>10GB Storage</Text>
              <Text>100K API Requests</Text>
              <Text>24/7 Support</Text>
            </Box>
            <Box flex={1} mx={4}>
              <Heading as="h2" size="lg" mb={2}>
                Pro
              </Heading>
              <Text fontSize="xl" mb={2}>
                $19.99/month
              </Text>
              <Text>50GB Storage</Text>
              <Text>500K API Requests</Text>
              <Text>24/7 Support</Text>
            </Box>
            <Box flex={1} ml={4}>
              <Heading as="h2" size="lg" mb={2}>
                Enterprise
              </Heading>
              <Text fontSize="xl" mb={2}>
                Contact Us
              </Text>
              <Text>Unlimited Storage</Text>
              <Text>Custom API Limits</Text>
              <Text>24/7 Priority Support</Text>
            </Box>
          </Flex>
          <Button colorScheme="blue">Get Started</Button>
        </Box>
      </Flex>
    </Box>
  );
};

FEAAS.registerComponent(PricingPage, {
  name: 'clientside-only',
  title: 'Clientside-only component',
  description: 'This is a Sleek Pricing Page Generated by AI',
  thumbnail: 'https://mss-p-006-delivery.stylelabs.cloud/api/public/content/3997aaa0d8be4eb789f3b1541bd95c58',
  group: 'AI Generated Components',
});

export default PricingPage;