'use client'
import * as FEAAS from '@sitecore-feaas/clientside/react'  
import React from 'react';  
import { Box, Image, Flex, Heading, Text } from '@chakra-ui/react';  
  
const ProductCard = ({ productImage, title, subtitle, price }) => {  
  return (  
    <Box borderWidth="1px" borderRadius="lg" overflow="hidden">  
      <Image src={productImage} alt={title} />  
  
      <Box p="6">  
        <Box flex="1" alignItems="baseline">  
          <Heading as="h2" color="red" fontSize="xl">  
            {title}  
          </Heading>  
        </Box>  
  
        <Text as="h3" color="gray.500" fontSize="md">  
          {subtitle}  
        </Text>  
  
        <Box mt="2">  
          <Text fontWeight="bold" fontSize="2xl">  
            ${price}  
          </Text>  
        </Box>  
      </Box>  
    </Box>  
  );  
};  
  
FEAAS.registerComponent(ProductCard, {  
  name: 'ProductCard',  
  title: 'Product Card',  
  description: 'This is a Product Card Generated by AI',  
  thumbnail: 'https://mss-p-006-delivery.stylelabs.cloud/api/public/content/3997aaa0d8be4eb789f3b1541bd95c58',  
  group: 'AI Generated Components',  
  required: ['productImage', 'title', 'price'],  
  properties: {  
    productImage: {  
      type: 'string',  
      title: 'Product Image'  
    },  
    title: {  
      type: 'string',  
      title: 'Title'  
    },  
    subtitle: {  
      type: 'string',  
      title: 'Subtitle'  
    },  
    price: {  
      type: 'number',  
      title: 'Price'  
    }  
  }  
});  
  
export default ProductCard;  
